### ISSUE TITLE
 message.gFOF = status[1] IndexError: list index out of rang

### ISSUE THREAD

**Issue by Raviteja-T** [Osaka-University-Harada-Laboratory/onrobot#11]
Traceback (most recent call last):
  File "/home/toor/catkin_ws/devel/lib/onrobot_rg_control/OnRobotRGTcpNode.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/toor/catkin_ws/src/onrobot/onrobot_rg_control/nodes/OnRobotRGTcpNode.py", line 90, in <module>
    OnRobotRGTcp()
  File "/home/toor/catkin_ws/src/onrobot/onrobot_rg_control/nodes/OnRobotRGTcpNode.py", line 50, in __init__
    self.mainLoop()
  File "/home/toor/catkin_ws/src/onrobot/onrobot_rg_control/nodes/OnRobotRGTcpNode.py", line 68, in mainLoop
    status = self.gripper.getStatus()
  File "/home/toor/catkin_ws/src/onrobot/onrobot_rg_control/src/onrobot_rg_control/baseOnRobotRG.py", line 107, in getStatus
    message.gFOF = status[1]
IndexError: list index out of rang

**Comment by takuya-ki** [comment]
@Raviteja-T
Please carefully explain the condition when you faced this error and change the title so that we can understand what kind of issue this is.
The title is not the place to copy and paste the error.
